export const strings = {
  welcome_message:'Welcome to visa yard backend',
  user_exist:"User already exists",
  otp_send:"Otp send to your mobile number",
  user_not_found: 'User not found',
  otp_expired:"Otp has expired",
  invalid_otp:"Invalid otp",
  user_verified:"Email verified successfully",
  otp_resend:"otp resend successfully",
  user_created: 'User created successfully',
  err_unknown_error: 'Unknown error',
  err_foreign_key_error: 'Foreign key constraint error',
  msg_item_exists: 'Item already exists',
  err_database_error: 'Database error occurred',
  err_internal_error_occurred: 'Internal server error occurred',
  password_does_not_match: 'Password does not match',  
  user_logged_in: 'User logged in successfully',
  visa_created:'Visa created successfully',
  get_visa:'Visa fetched successfully',
  visa_not_found:'Visa not found',
  invalid_json:'Invalid JSON format for progressBar or popularMentions',
  user_not_verified:'User is not verified',
  invalid_password:'Invalid password',
  invalid_email:'Invalid email',
  invalid_name:'Invalid name',
  missing_visa_id:'Missing Visa ID to update data',
  visa_updated:'Visa updated successfully',
  invalid_step:'Invalid step',
  basic_details_updated:"Basic details added successfully",
  pricing_updated:"Pricing updated successfully",
  visa_details_updated:"Visa details updated successfully",
  visa_progress_updated:"Visa progressupdated successfully",
  addtional_details_updated:"Additional details updated successfully",
  email_required:'Email is required',
  otp_verified:'OTP verified successfully',
  user_updated:'User updated successfully',
  user_found:'User fetched successfully',
  documents_updated:'Visa documents updated successfully',
  invalid_credentials:'Invalid credentials',
  login_success:'Login successfully',
  visa_deleted:'Visa deleted successfully',
  no_token_provided:'Unauthorized: No token provided',
  invalid_token:'Unauthorized: Invalid token',
  you_dont_have_access:'Unauthorized: You do not have access',
  token_expired:'Session expired please login again',
  matched_visa_not_found:'No matched visas found',
  matched_visa_application_not_found:'No matched visa application found',
  passport_require:"You need to upload passport",
  visa_app_found:"Visa application fetched successfully",
  visa_app_status_updated:"Visa status updated successfully",
  category_add:"Category added successfully",
  categories_fetched:"Category fetched successfully",
  category_deleted:"Category deleted successfully",
  category_not_found:"Category not found",
  category_id_required:"Category id is required",
  category_updated:"Category updated successfully",
  category_fetched:"Category fecthed successfully",
  visatype_created:"Visatype added successfully",
  visatype_fetched:"Visatype fetched successsfully",
  visatype_deleted:"Visatype deleted successfully",
  visatype_updated:"Visatype updated successfully",
  visatype_not_found:"Visatype not found",
  visatype_id_required:"Visa type id is required",
  childuser_create:"Member added successfully",
  child_user_not_found:"Child user not found",
  child_users_fetched:"Child users fetched successfully",
  visa_app_deleted:"Visa application deleted successfully",
  child_user_deleted:"Child user deleted successfully",
  id_required:"Parent userId or child id is missig",
  photo_uploaded:"Photo uploaded successfully",
  internal_server_error:"Internal server error",
  valid_passport_required:"Valid passport required",
  passport_valid:"Passport expirey date must be less then six month", 
  passport_uploaded:"Passport uploaded successfully",
  additional_details_updated:"Additional details updated successfully",
  max_child_users:"Maximum number of child users 9 reached",
  missing_required_fields:"Missing required fields",
  child_application_exists:"Already created application",
  child_user_fetched:"Child user fetched successfully",
  visa_application_created:"Visa application is created",
  missing_id:"Id is required",
  cover_images_length_error:"Cover images must be an array.",
  cover_images_length_less_6:"Cover images length should not be less then 6.",
  cover_images_length_more_6:"Cover images length should not be more then 6.",
  username_exists:"Username already exists",
  staff_created:"Staff created successfully",
  staff_list_fetched:"Staff list fetched successfully",
  staff_not_found:"Staff not found",
  staff_fetched:"Staff fetched successfully",
  staff_updated:"Staff updated successfully",
  staff_deleted:"Staff deleted successfully",
  
};