# Generated by Django 5.0.1 on 2024-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plan_user_available_credit_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='is_paid',
            field=models.BooleanField(db_column='is_paid', default=False),
        ),
    ]
