# Generated by Django 5.0.1 on 2024-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userplan_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='payment_method',
            field=models.CharField(blank=True, db_column='payment_method', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='transaction_id',
            field=models.CharField(blank=True, db_column='transaction_id', max_length=255, null=True),
        ),
    ]
