import AppLayout from "@/Layout/AppLayout";
import inter from "@/utils/fontConfig";
import "./globals.css";

export const metadata = {
  title: "Virtual Lights",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/assets/logo.svg", type: "image/svg+xml" }],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
