const Images = {
  logo: require('../assets/images/logo.png'),
  email: require('../assets/images/email.png'),
  password: require('../assets/images/pass.png'),
  home: require('../assets/images/home.png'),
  home_unselect: require('../assets/images/home_unselect.png'),
  order_select: require('../assets/images/order_select.png'),
  order: require('../assets/images/orders.png'),
  profile_select: require('../assets/images/profile_select.png'),
  profile: require('../assets/images/profile.png'),
  cart: require('../assets/images/cart.png'),
  notify: require('../assets/images/notify.png'),
  notify_select: require('../assets/images/notify_select.png'),
  bell: require('../assets/images/bell.png'),
  lights_slider: require('../assets/images/lights_slider.png'),
  slider_bg: require('../assets/images/slider_bg.png'),
  bulb: require('../assets/images/bulb.png'),
  big_bulb: require('../assets/images/big_bulb.png'),
  addCart: require('../assets/images/addCart.png'),
  drawer: require('../assets/images/drawer.png'),
  men: require('../assets/images/men.png'),
  women: require('../assets/images/women.png'),
  beauty: require('../assets/images/beauty.png'),
  eye_wear: require('../assets/images/eye_wear.png'),
  order_complete: require('../assets/images/order_complete.png'),
  delivery: require('../assets/images/delivery.png'),
  on_way: require('../assets/images/on_way.png'),
  passCreated: require('../assets/images/passCreated.png'),
  dummy_profile: require('../assets/images/dummy_profile.png'),
  notification1: require('../../assets/images/notification1.png'),
  menu: require('../../assets/images/menu.png'),
  active_home:require('../../assets/images/bottombar/active/home.png'),
  active_lead:require('../../assets/images/bottombar/active/lead.png'),
  active_order:require('../../assets/images/bottombar/active/order.png'),
  active_activity:require('../../assets/images/bottombar/inactive/activity.png'),
  inactive_home:require('../../assets/images/bottombar/inactive/home.png'),
  inactive_lead:require('../../assets/images/bottombar/inactive/lead.png'),
  inactive_order:require('../../assets/images/bottombar/inactive/order.png'),
  inactive_activity:require('../../assets/images/bottombar/inactive/activity.png'),
  back: require('../../assets/images/back.png'),
  filter: require('../../assets/images/filter.png'),
  dealers: require('../../assets/images/drawer/dealer.png'),
  logout: require('../../assets/images/drawer/logout.png'),
  manufacture: require('../../assets/images/drawer/manufacture.png'),
  staff: require('../../assets/images/drawer/staff.png'),
  setting: require('../../assets/images/drawer/setting.png'),
  inprogress: require('../../assets/images/inprogress.jpg'),
  completed: require('../../assets/images/completed.jpg'),
  cancelled: require('../../assets/images/cancelled.jpg'),  
  ongoing: require('../../assets/images/ongoing.jpg'),
  recent_activity: require('../../assets/images/activity.png'),
  user: require('../../assets/images/user.png'),
  edit: require('../../assets/images/edit.png'),
  slider_filter: require('../assets/images/slider.png'),
  mask_blub:require('../../assets/images/mask_group.png'),
  home_icon: require('../../assets/images/bottombar/home_icon.png'),
  order_icon: require('../../assets/images/bottombar/order_icon.png'),
  profile_icon: require('../../assets/images/bottombar/profile_icon.png'),
  cart_icon: require('../../assets/images/bottombar/cart_icon.png'),
  lead_icon: require('../../assets/images/group.png'),
  activity_icon: require('../../assets/images/routine.png'),
  slider_bg1: require('../../assets/images/carousel/bg1.jpeg'),
  slider_bg2: require('../../assets/images/carousel/bg2.jpeg'),
  slider_bg3: require('../../assets/images/carousel/bg3.jpeg'),
  slider_bg4: require('../../assets/images/carousel/bg4.jpeg'),
  slider_bg5: require('../../assets/images/carousel/bg5.jpeg'),
  recycle_bin:require('../../assets/images/recycle-bin.png'),
  calendar:require('../../assets/images/calendar.png'),
  plus:require('../../assets/images/plus.png'),
  complaints:require('../../assets/images/complain.png')
};

export default Images;
