

const Routes = {
  Home: 'Home',
  Login: 'Login',
  Splash: 'Splash',
  Profile: 'Profile',
  Notify: 'Notify',
  Cart: 'Cart',
  Orders: 'Orders',
  ProductDetail: 'ProductDetail',
  BottomStack: 'BottomStack',
  YourCart: 'YourCart',
  Checkout: 'Checkout',
  OrderDetails: 'OrderDetails',
  ForgotPassword: 'ForgotPassword',
  CreatePassword: 'CreatePassword',
  ForgotOTP: 'ForgotOTP',
  MyWishlist: 'MyWishlist',
  ChangePassword:'ChangePassword',
  NewEditProfile: 'NewEditProfile',
  NewLogin: 'NewLogin',
  Dashboard: 'Dashboard',
  AdminOrder: 'AdminOrder',
  AdminLeads: 'AdminLeads',
  AdminActivity: 'AdminActivity',
  AdminBottomStack: 'AdminBottomStack',
  AdminStaff: 'AdminStaff',
  AdminDealers: 'AdminDealers',
  AdminManufacturer: 'AdminManufacturer',
  DrawerStack: 'DrawerStack',
  SignUp: 'SignUp',
  AdminStaffProfile: 'AdminStaffProfile',
  AdminProducts: 'AdminProducts',
  AdminStaffEditProfile: 'AdminStaffEditProfile',
  AdminLeadView: 'AdminLeadView',
  AdminDealersProfile: 'AdminDealersProfile',
  AdminDealersOrder: 'AdminDealersOrder',
  AdminDealersEditProfile: 'AdminDealersEditProfile',
  AdminCustomer: 'AdminCustomer',
  AdminCustomerProfile: 'AdminCustomerProfile',
  AdminCustomerEditProfile: 'AdminCustomerEditProfile',
  AdminCustomerOrder: 'AdminCustomerOrder',
  AdminOrdersDetail: 'AdminOrdersDetail',
  AdminProfile: 'AdminProfile',
  AdminEditProfile: 'AdminEditProfile',
  SelectStaff: 'SelectStaff',
  AdminDealerOrderDetail: 'AdminDealerOrderDetail',
  AdminCustomerOrderDetail: 'AdminCustomerOrderDetail',
  Address: 'Address',
  AddAddress: 'AddAddress',
  AddOrder: 'AddOrder',
  AdminNotification: 'AdminNotification',
  Review:"Review",
  RecycleBin:"RecycleBin",
  ProgressReport:"ProgressReport",
  ManageLead:"ManageLead",
  AddProduct:"AddProduct",
  LeadStaff:"LeadStaff",
  AddCategory:"AddCategory",
  ViewProduct:"ViewProduct",
  ViewOrder:"ViewOrder",
  ViewLead:"ViewLead",
  ViewComplaints:"ViewComplaints",
  ViewStaff:"ViewStaff",
  ManageNote:"ManageNote",
  AdminComplaints:"AdminComplaints",
  AdminViewComplaints:"AdminViewComplaints",
  AdminComplaintStaff:"AdminComplaintStaff",
  ViewAdminTodayLead:"ViewAdminTodayLead",
  ViewAdminTodayOrder:"ViewAdminTodayOrder"
};

export default Routes;
