interface ClinicalData {
  id?: number;
  name?: string;
  dateApproved?: string;
  approvedBy?: string;
  hourlyRate?: string;
  responseRate?: string;
  completedJobs?: number;
  activeJobs?: number;
}
export const clinicalData: ClinicalData[] = [
  {
    id: 1,
    name: "Trent Graham",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 2,
    name: "Haylee Owen",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 3,
    name: "Trent Graham",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 4,
    name: "Flynn James",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 5,
    name: "Trent Graham",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 6,
    name: "Gideon Perez",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 7,
    name: "Zyaire Dejesus",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 8,
    name: "Zara Yu",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 9,
    name: "Zara Yu",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 10,
    name: "Zara Yu",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 11,
    name: "Zara Yu",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 12,
    name: "Zara Yu",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
  {
    id: 13,
    name: "Zara Yu",
    dateApproved: "05.02.2025",
    approvedBy: "Reuben Hale",
    hourlyRate: "£18.00",
    responseRate: "98%",
    completedJobs: 103,
    activeJobs: 5,
  },
];
