export const Images = {
  detail: require('../../assets/images/details.png'),
  photo: require('../../assets/images/photo.png'),
  scanner: require('../../assets/images/scanner.png'),
  connect: require('../../assets/images/connect.png'),
  no_data: require('../../assets/images/No_data.gif'),
  scanner_loading: require('../../assets/images/user_scanner.gif'),
  docs_scanner: require('../../assets/images/docs_scanner.gif'),
  check: require('../../assets/images/check.png'),
  select_check: require('../../assets/images/select_check.png'),
  user: require('../../assets/images/user.png'),
  watch: require('../../assets/images/watch.png'),
  calender: require('../../assets/images/calender.png'),
  calenderTick: require('../../assets/images/calendertick.png'),
  appIcon: require('../../assets/images/app_logo.png'),
  // consult: require('../../assets/images/consult.gif'),
  home_banner: require('../../assets/images/home_banner.png'),
  consult: require('../../assets/images/consult.png'),
  login1: require('../../assets/images/login1.png'),
  login2: require('../../assets/images/login2.png'),
  login3: require('../../assets/images/login3.png'),
  login4: require('../../assets/images/login4.png'),
  login5: require('../../assets/images/login5.png'),
  login6: require('../../assets/images/login6.png'),
  login7: require('../../assets/images/login7.png'),
  login8: require('../../assets/images/login8.png'),
  login9: require('../../assets/images/login9.png'),
  login10: require('../../assets/images/login10.png'),
  login11: require('../../assets/images/login11.png'),
  login12: require('../../assets/images/login12.png'),
  documents: require('../../assets/images/google_docs.png'),
  new_app_logo: require('../../assets/images/visayard_logo2.png'),
  checked: require('../../assets/images/checked.png'),
  new_app_logo2: require('../../assets/images/app_logo2.png'),

  bank_icon: require('../../assets/images/visadetails/bank.png'),
  entry_icon: require('../../assets/images/visadetails/entry.png'),
  income_icon: require('../../assets/images/visadetails/income.png'),
  passport_icon: require('../../assets/images/visadetails/passport.png'),
  photo_icon: require('../../assets/images/visadetails/photo.png'),
  stay_icon: require('../../assets/images/visadetails/stay.png'),
  validity_icon: require('../../assets/images/visadetails/validity.png'),
  visatype_icon: require('../../assets/images/visadetails/visa_type.png'),
  hotel_icon: require('../../assets/images/visadetails/hotel.png'),
  insurance_icon: require('../../assets/images/visadetails/insurance.png'),
  single_icon: require('../../assets/images/visadetails/single.png'),
  group_icon: require('../../assets/images/visadetails/group.png'),
  active_radio: require('../../assets/images/active_radio.png'),
  inactive_radio: require('../../assets/images/inactive_radio.png'),

  upload_icon: require('../../assets/images/upload.png'),
  camera_icon: require('../../assets/images/camera.png'),
  right_icon:require('../../assets/images/right-arrow.png'),
  new_passport_icon:require('../../assets/images/passport.png'),
  plan_icon:require('../../assets/images/airplane.png'),
  plus_icon:require('../../assets/images/plus.png'),

  profile:require('../../assets/images/profile/profile.png'),
  application:require('../../assets/images/profile/application.png'),
  help:require('../../assets/images/profile/help.png'),
  persona:require('../../assets/images/profile/persona.png'),
  logout:require('../../assets/images/profile/logout.png'),

  incomeTax:require('../../assets/images/profile/incometax.png'),
  adhar:require('../../assets/images/profile/adhar.png'),
  passportBack:require('../../assets/images/profile/passportBack.png'),
  passportFront:require('../../assets/images/profile/passportFront.png'),
  pancard:require('../../assets/images/profile/pancard.png'),
  payment_details:require('../../assets/images/visadetails/credit.png'),
  applicants:require('../../assets/images/visadetails/categories.png'),
  status:require('../../assets/images/visadetails/status.png'),
  info:require('../../assets/images/visadetails/info.png'),
  list:require('../../assets/images/visadetails/list.png'),
};
