import type { Metadata } from "next";
import "./globals.css";
//relative path imports
import MainLayout from "@/layouts";

export const metadata: Metadata = {
  title: "Zorbee Super Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
