#  def node_require(script)
#    require Pod::Executable.execute_command('node', ['-p',
#      "require.resolve(
#        '#{script}',
#        {paths: [process.argv[1]]},
#      )", __dir__]).strip
#  end


#  node_require('react-native/scripts/react_native_pods.rb')
#  node_require('react-native-permissions/scripts/setup.rb')

# platform :ios, min_ios_version_supported
# prepare_react_native_project!

# setup_permissions([
#   'Camera',
#   'LocationWhenInUse',
#   'PhotoLibrary'
# ])


# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'VizaYard' do
#   config = use_native_modules!
#   use_frameworks! :linkage => :static
#   $RNFirebaseAsStaticFramework = true
#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   target 'VizaYardTests' do
#     inherit! :complete
#     # Pods for testing
#   end
#   permissions_path = '../node_modules/react-native-permissions/ios'

#   pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
#   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
#   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
#   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  
#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

# You can also define a helper to load those dynamically (optional):
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Load setup scripts via node if you prefer dynamic resolution
# node_require('react-native/scripts/react_native_pods.rb')
# node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'Camera',
  'LocationWhenInUse',
  'PhotoLibrary',
  'Notifications'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'VizaYard' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'VizaYardTests' do
    inherit! :complete
    # Pods for testing
  end

  # Optional if you manually added these pods (but not needed if using setup_permissions)
  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  # pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

