# Generated by Django 5.0.1 on 2024-02-03 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_collection_result_table_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.UUIDField(db_column='plan_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('plan_name', models.CharField(db_column='plan_name', max_length=255)),
                ('plan_description', models.TextField(blank=True, db_column='plan_description', null=True)),
                ('credit', models.IntegerField(db_column='credit')),
                ('amount', models.FloatField(db_column='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_selectable', models.BooleanField(db_column='is_selectable', default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='available_credit',
            field=models.PositiveIntegerField(db_column='available_credit', default=1),
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('user_plan_id', models.UUIDField(db_column='user_plan_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('purchased_on', models.DateTimeField(auto_now_add=True, db_column='purchased_on')),
                ('transaction_id', models.CharField(blank=True, db_column='transaction_id', null=True)),
                ('payment_method', models.CharField(blank=True, db_column='payment_method', null=True)),
                ('plan', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='api.plan')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
